### PR TITLE
Clearing up one inconsistency in the interactive chapter.

### PR DESCRIPTION
**Pull request by gvwilson**
FIXME: `bin/mismatch.py -d interactive en` reports several other inconsistencies.  All of them arise because we are using `app.js` as a filename in the chapter for intermediate versions of the code, but only have one such file (the finished one) under `src`.

### CODE REVIEW

**Comment by tobyhodges** [comment]
How would you prefer that I handle this?

1. Merge as-is
2. Create intermediate files, `app-intermediate-1.js`, `app-intermediate-2.js`, etc
3. Implement some way of telling `mismatch.py` to ignore intermediate snippets like these

**Comment by gvwilson** [comment]
Intermediate files seems like the most robust approach...

**Comment by tobyhodges** [comment]
Delighted that you agree

**Comment by tobyhodges** [comment]
`bin/mismatch.py -d interactive en` now runs clean.

**Pull request merged**
