### PR TITLE
change "parent" arrow label to "parent class"

### PR DESCRIPTION
**Pull request by tobyhodges**
I suggest changing label text to "parent class" to reduce risk of confusion with the variable we're also calling `parent` in the example.

### CODE REVIEW

**Comment by tobyhodges** [comment]
Actually, looking at it again I think that the column headings should be changed too: at the moment the figure has two column headings, both "__Variables__". I would suggest to create three - "__Variables__", "__Attributes__", and "__Values__"

**Comment by gvwilson** [comment]
Diagram updated - master of each chapter's figures is in files/CHAPTER.xml, edited with draw.io, then exported as SVG with 4-pixel boundary, transparency, and *without* embedding a copy of the original diagram in the SVG.

**Comment by tobyhodges** [comment]
Ok, thanks. I'll use draw.io next time.

**Comment by gvwilson** [comment]
I really oughta document that somewhere, oughtn’t I? :-)

**Pull request merged**
