### PR TITLE
Typo in utilities.js {in -> of}

### PR DESCRIPTION
**Pull request by sa-lee**
The output of running src/basics/import.js in the web version does not match up with the code provided in utilties.js

### CODE REVIEW

**Comment by sa-lee** [comment]
also can i say i'm really enjoying the book and learning heaps, thanks for writing it!

**Comment by gvwilson** [comment]
Hi - what output are you seeing?  When I run:

```
cd src/basics
node import.js
```

I get exactly the output shown (at rev 2147d5a1d278).

**Comment by sa-lee** [comment]
Sorry I meant that on the website when I look at this [section](https://software-tools-in-javascript.github.io/js-vs-ds/en/basics/#s:basics-modules) I see:


screenshot 2019-01-25 11 24 05


If then go and run with the code given in the screenshot as instructed

```
node import.js

clip(-1,5,3,0,10) -> -1,3,0

clip(-1,5,3,0,10, 5) -> -1,5,3,0

```
The output is different to what is given in the book 
image

which I thought is due to there being a typo in `utilities.js`.

**Comment by gvwilson** [comment]
Aaaah - yes, you're right, the `for-in` should be a `for-of`. Fixed pushed - thanks very much for catching this.

**Pull request closed without merging**
