### PR TITLE
Starting to rewrite the capstone exercise.

### PR DESCRIPTION
**Pull request by gvwilson**
Got as far as "The Display" section - haven't introduced CORS yet.

### CODE REVIEW

**Comment by tobyhodges** [comment]
I'm running out of time to work on this today but I have isolated the (should that be "a"?) problem: the DataManager is not returning what you think it's returning/what used to be returned by the SQL queries in the Old Way/what the `src/capstone/front/Data*.js` components expect.

These components want an array of statistics aggregated by year, but we are currently passing them an aggregation of the whole subset of data chosen, which they don't know what to do with. 

To fix this, I need to remember how to do these kinds of aggregation operations in JS, which I no longer have the mental dexterity for on this Sunday evening. I will get back to it tomorrow, unless you get there first.

**Comment by tobyhodges** [comment]
No worries. I should have time to fix it tomorrow.

**Comment by gvwilson** [comment]
I fixed the capstone example (I think) - part of the problem was that column names had changed on the back end but not the front end. The other is that we have to filter out NaN's when using Math.min, Math.max, and other functions, otherwise the result is NaN - R has spoiled me. The changes to `src/back/data-manager.js` will have to be taken back to `src/dataman` and explained, but I think the code is running.

**Comment by tobyhodges** [comment]
I have updated the capstone to filter out empty years, which I think improves the layout quite a lot. 

### Before
screen shot 2018-12-10 at 15 13 44

### After
screen shot 2018-12-10 at 15 31 30


I dealt with the warning React from react about needing unique keys too. In doing the latter, I found that I am probably dealing with it quite badly (and explained it incorrectly) in the interactive chapter, so going to go back and fix that now, along with updating dataman.

**Comment by gvwilson** [comment]
Nice - is this ready to merge?

**Comment by tobyhodges** [comment]
Give me a few minutes to update the chapter text

**Comment by tobyhodges** [comment]
This is ready to merge

**Pull request merged**
