### PR TITLE
Prepping overhaul of capstone

### PR DESCRIPTION
**Pull request by gvwilson**
Starting to revise capstone exercise to use Parcel and Vega-Lite.

### CODE REVIEW

**Comment by tobyhodges** [comment]
I'll look at this today

**Comment by gvwilson** [comment]
I still need to fill in the last step (adding the chart to the display) - unless you want to do that to check your understanding of the Vega-Lite stuff, and I'll work on discussion of CORS and figure out where we ought to have introduced Winston (the logging framework)?

**Comment by tobyhodges** [comment]
yeah, let me have a go at it. It should help me to test my understanding.

**Comment by gvwilson** [comment]
Sold! I'm going to try to write a readable-by-humans explanation of the madness that is CORS. Iä! Iä! Web security fhtagn!

**Pull request merged**
