### PR TITLE
Create blurb.txt

### PR DESCRIPTION
**Pull request by tobyhodges**
Too long?
Too repetitive?
Too far from the point?

### CODE REVIEW

**Comment by gvwilson** [comment]
I'll take a whack at it. Any word on a cover image?
Cheers,
Greg

**Comment by tobyhodges** [comment]
The short answer is "no". I may have an hour or so to work on it now...

**Comment by gvwilson** [comment]
Any ideas about what you want to use? Been struggling to think of something funny but not forced-funny, if you know what I mean.

**Comment by tobyhodges** [comment]
Something with [a rhino](http://shop.oreilly.com/product/9780596805531.do)?

**Comment by gvwilson** [comment]
I'd like to use the Cthulhu logo, but the creator hasn't ever responded to my pings, and it's under a non-commercial license.  Maybe Cthulhu at a keyboard? :-)

**Comment by tobyhodges** [comment]
Almost certainly beyond my artistic ability. I am good at geometric shapes. (Well, the computer is good at geometric shapes.)

**Comment by tobyhodges** [comment]
Love the choice of cover image. Very appropriate.

**Pull request merged**
